With Apollo GraphQL Example
jaredpalmer/razzle pull request #1024
Opened 2019-06-03 15:12 UTC by EbrahimKreem

Add an example of Razzle with Apollo GraphQL

2019-07-10 20:12 UTC, OnuPete commented on examples/with-react-apollo/src/lib/apollo.js
> +        fetchPolicy: "cache-and-network"
query's fetchPolicy does not have "cache-and-network". watchQuery on the other hand does contain "cache-and-network".

2019-07-11 08:19 UTC, adaam2 approved these changes

2019-07-11 08:19 UTC, adaam2 commented on examples/with-react-apollo/package.json
> +}
New line at EOF please

2019-07-17 09:13 UTC, kkalavantavanich commented
Is this the same as #950?

2019-07-17 14:21 UTC, jaredpalmer requested changes
Thank you for this! 

Overall, this looks a bit more opinionated than I think we want for a "bare bones" example. A few things to change/discuss.

- Should we consider using `apollo-boost` for the "bare-bones" example and maybe add another example called `with-apollo-client` or like `with-apollo-advanced`? cc @peggyrayzis 
- Add comments in areas where people should change up variables
- Elaborate what is going on in the README. One sentence about what Apollo is and then a paragraph about this gestault of this example--calling out what folks will want to change as well.
-

2019-07-17 14:21 UTC, jaredpalmer commented on examples/with-react-apollo/README.MD
> +This is a basic, bare-bones example of how to use razzle with apollo.
This could use some more information. Also should have a link to Apollo repo and docs

2020-06-04 18:41 UTC, matiasherranz commented on examples/with-react-apollo/README.MD
> +curl https://codeload.github.com/jaredpalmer/razzle/tar.gz/master | tar -xz --strip=2 razzle-master/examples/with-react-apollo
```
curl https://codeload.github.com/jaredpalmer/razzle/tar.gz/master | tar -xz --strip=2 razzle-master/examples/with-react-apollo
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  626k    0  626k    0     0   334k      0 --:--:--  0:00:01 --:--:--  334k
tar: razzle-master/examples/with-react-apollo: Not found in archive
tar: Error exit delayed from previous errors.
```

2020-09-22 20:28 UTC, fivethreeo commented
Coud you do this against the finch release and use the razzle graphql plugin?

2020-09-24 20:40 UTC, matiasherranz commented
> Could you do this against the finch release and use the razzle graphql plugin?

What do you mean with " the finch release"? If provided with some context, I'll be happy to help/provide more info/test again.

Thanks for the follow up!

2020-09-24 22:43 UTC, fivethreeo commented
There is two development releases now. A canary that is a development release for 3.x and a finch that is a development release for 4.x with webpack 5 support. I prioritize new features and support for 4.x. So if this is done against the finch branch in git it will be forwards compatible. To get a basic example up and running: npx create-razzle-app@finch my-app; cd my-app; yarn start

2020-09-24 22:47 UTC, fivethreeo commented
So yarn add razzle@finch —dev

2022-12-17 17:33 UTC, closed without merging