fix (razzle #1704) by adding support for webpack-dev-server v4
jaredpalmer/razzle pull request #1730
Opened 2021-10-14 01:07 UTC by heath-freenome

Fixes #1704 

- Updated `package.meta.json` and `packages/razzle-dev-utils/package.json` to allow for v3 and v4 of `webpack-dev-server`
- Updated `createConfigAsync.js` to build the correct `devServer` config for v3 or v4 based on the extracted version from `webpack-dev-server`'s version from the `package.json`
- Added a new `with-webpack-dev-server-v4` example

2021-10-14 16:36 UTC, heath-freenome commented
@fivethreeo Here you go!

2021-10-14 16:55 UTC, fivethreeo requested changes
Maybe use?

```js
const devserverVersion = require("webpack-dev-server/package.json").version;
console.log(devserverVersion);
```

2021-10-14 16:55 UTC, fivethreeo commented on packages/razzle/config/createConfigAsync.js
> +        if (razzleOptions.enableDevServerV4) {
Maybe use?

```js
const devserverVersion = require("webpack-dev-server/package.json").version;
console.log(devserverVersion);
```

2021-10-14 21:41 UTC, heath-freenome commented on packages/razzle/config/createConfigAsync.js
> +        if (razzleOptions.enableDevServerV4) {
@fivethreeo Ok, after a little trial and error, I went with this approach. Let me know how it looks now

2021-10-14 21:56 UTC, fivethreeo commented on packages/razzle/config/createConfigAsync.js
> +        const devserverPkg = require('webpack-dev-server/package.json');
Move to top of file so it won't compute every time.

2021-10-14 21:56 UTC, fivethreeo commented on packages/razzle/config/createConfigAsync.js
> +          devServer = {
Maybe sett 3 and 4 common options and do special cases for each version, use Object.assign?

2021-10-14 22:16 UTC, heath-freenome commented on packages/razzle/config/createConfigAsync.js
> +        const devserverPkg = require('webpack-dev-server/package.json');
I just moved the require

2021-10-14 23:28 UTC, heath-freenome commented on packages/razzle/config/createConfigAsync.js
> +          devServer = {
Done

2021-10-15 00:05 UTC, fivethreeo commented on packages/razzle/config/createConfigAsync.js
> +        const devServerMajorVersion = parseInt(devserverPkg.version[0]);
Can move this one up too.

2021-10-15 00:16 UTC, heath-freenome commented on packages/razzle/config/createConfigAsync.js
> +        const devServerMajorVersion = parseInt(devserverPkg.version[0]);
Done

2021-10-15 11:06 UTC, merged

2021-10-15 16:57 UTC, heath-freenome commented
@fivethreeo when will this fix be available in a razzle release?

2021-10-15 22:58 UTC, fivethreeo commented
now :)

2021-10-16 04:08 UTC, chrisdostert commented
@fivethreeo It looks like with webpack-dev-server 4, the module casing changed from `webpack-dev-server/client/utils/createSocketUrl` to `webpack-dev-server/client/utils/createSocketURL` at https://github.com/jaredpalmer/razzle/blob/776725f862bb996210e2c69631dc5233c9b2b873/packages/razzle-dev-utils/webpackHotDevClient.js#L15 . Otherwise we get 
```
 WARNING in ./node_modules/webpack-dev-server/client/utils/createSocketURL.js
[1] There are multiple modules with names that only differ in casing.
[1] This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
[1] Use equal casing. Compare these module identifiers:
[1] * /src/node_modules/webpack-dev-server/client/utils/createSocketURL.js
```

2021-10-16 04:42 UTC, fivethreeo commented
Will need to test for version there aswell. But do we really have to swap out the client anymore with newer dev server?

2021-10-16 15:38 UTC, fivethreeo commented
released 4.2.1 with module path fix

2021-10-17 12:35 UTC, fivethreeo commented
released 4.2.2 with reverted module path fix, issue with filename seems to be a webpack-dev-server issue

2021-10-19 17:42 UTC, heath-freenome commented
> released 4.2.2 with reverted module path fix, issue with filename seems to be a webpack-dev-server issue

Is there an issue with `webpack-dev-server` for that?

2021-10-19 17:44 UTC, fivethreeo commented
@chrisdostert reported issues with createSocketURL