Add with-pwa example
jaredpalmer/razzle pull request #672
Opened 2018-06-19 12:23 UTC by rhodee

Example with [Workbox](https://github.com/GoogleChrome/workbox) and [WebpackPWAManifest](https://github.com/arthurbergmz/webpack-pwa-manifest) Webpack plugins.

Most of the action is in `razzle.config.js`. The file `src/registerServiceWorker.js` was added and `src/index.js` was modified from the basic implementation.

2018-06-19 20:20 UTC, lucasterra commented
Maybe [write a plugin](https://github.com/jaredpalmer/razzle#writing-plugins) for this instead?

2018-06-21 12:53 UTC, jaredpalmer commented on examples/with-pwa/package.json
> +  "name": "my-razzle-app",
change pkg name to `razzle-examples-with-pwa` for congruency

2018-06-21 12:56 UTC, jaredpalmer requested changes
We can move the razzle-plugin-with-pwa discussion elsewhere I guess, but after you change the package name, this looks great. Thanks!

2018-06-21 12:56 UTC, jaredpalmer commented on examples/with-pwa/razzle.config.js
> +    plugins: [{ func: modify }]
I'd prefer this API to be more inline with how the TS plugin works where you can pass an options object to the plugin.

2018-06-21 12:56 UTC, jaredpalmer commented on examples/with-pwa/src/server.js
> +    console.log(process.env)
Remove console.log

2018-08-27 13:25 UTC, closed without merging