Sync with CRA 2
jaredpalmer/razzle pull request #788
Opened 2018-10-22 17:06 UTC by olegreznichenko

I removed polyfills as did CRA 2
https://github.com/facebook/create-react-app/releases/tag/v2.0.3

2018-10-30 21:25 UTC, jaredpalmer commented on packages/razzle/config/createConfig.js
> +        client: [paths.appClientIndexJs],
```suggestion
        client: paths.appClientIndexJs, 
```

This will enable treeshaking in production. Right @thelarkinn?

2018-10-30 21:26 UTC, jaredpalmer requested changes
We can easily enable treeshaking with that one change i suggested

2018-10-30 21:29 UTC, jaredpalmer commented
We also need to add docs about this.

2018-11-08 17:59 UTC, olegreznichenko commented
@jaredpalmer docs are updated https://github.com/jaredpalmer/razzle/pull/788/files#diff-04c6e90faac2675aa89e2176d2eec7d8R230
Also, I resolved your comment

2018-11-15 20:39 UTC, jaredpalmer approved these changes

2018-11-15 21:08 UTC, merged