With sequelize example
jaredpalmer/razzle pull request #899
Opened 2019-01-27 14:19 UTC by mschipperheyn

With-sequelize example.

Highlights:
- Creates docker mysql container
- Creates database
- Seeds database
- Displays database contents on homepage

I can move this example to master if you prefer.

2019-01-28 14:12 UTC, jaredpalmer requested changes
This is epic! You rock! Some little nits here and there.

2019-01-28 14:12 UTC, jaredpalmer commented on examples/with-sequelize/README.md
> +The example comes with a `docker` container to bootstrap a database server. For this to work you should have `docker` installed. If you already have `mysql` installed and want to use that server inst
I like this. I think we should rework it to assume that you connect to sqllite with just dotenv vars at first. It’s a sequelize example after all. then at the bottom let’s document how to spin up local docker mysql and and postgres as well as just installing these with brew?

2019-01-28 14:12 UTC, jaredpalmer commented on examples/with-sequelize/README.md
> +The example comes with a `docker` container to bootstrap a database server. For this to work you should have `docker` installed. If you already have `mysql` installed and want to use that server inst
Actually screw sqllite, I’m fine with it as mysql or postgres  as long as we can use a locally installed dB in the example (without docker)

2019-01-28 14:12 UTC, jaredpalmer commented on examples/with-sequelize/src/Home.js
> +  async componentDidMount() {
This isn’t a good thing to promote. Refactor to just use promises. Make sure to include a polyfill for isomorphic fetch.

2019-01-28 14:12 UTC, jaredpalmer commented on examples/with-sequelize/src/server.js
> +app.get('/rest/users', async (req, res) => {
Add a comment that this is a rest API route and not rendering react

2019-01-28 14:12 UTC, jaredpalmer commented on examples/with-sequelize/src/sequelize/index.js
> +  if (process.env.NODE_ENV !== 'test') await seed(models, sequelize);
Add curly braces

2019-01-28 17:17 UTC, mschipperheyn commented
@jaredpalmer I have a question. I wonder if I should not perhaps add a test to promote api testing. The only thing is that I found that `globalSetup` and `globalTeardown` are not supported. Which is what I use to start a database server and force the creation of the table structure one time only. I test serially against a single database to prevent issues with various test creating and removing data and creating weird errors (I prefer integration testing against mock database testing).

I know some people like to use some wizardry to create a new database process with various ports to keep the parallel testing in place. I never tried it.

2020-02-25 19:11 UTC, elliottjro commented
@mschipperheyn for db setup, I usually put it into the package.json scripts as a setup and just add it as a requirement before running jest:

```json
"scripts": {
  "unit": "./jest-setup/migrate-db.js && ./jest-setup/seed-db.js && test"
}
```

where `migrate-db.js`
```js
const { spawn } = require('child-process-promise')

const run = async () => {
  const url = process.env.TEST_DB_URL = 'mysql://root@localhost:3306/database-test'
  try {
    await spawn('./node_modules/.bin/sequelize', ['db:migrate', `--url=${url}`], { stdio: 'inherit' })
    console.log('Migration success')
  } catch (e) {
    console.error('migration failed')
    process.exit(1)
  }
  process.exit(0)
}
run()
```

If you like, you can modify this PR (I know its quite old now, sorry for the delay) or I can just merge it in as is and you can make another PR when you have time to add this in?

2020-02-25 19:13 UTC, elliottjro approved these changes
Looks like all review change requests has been addressed

2020-03-13 13:55 UTC, nimaa77 commented
@elliottjro hello, why you don't merge this 😎?

2020-09-22 20:30 UTC, fivethreeo commented
Could you do this against the finch branch?

2020-10-04 20:01 UTC, closed without merging

2020-10-04 20:07 UTC, fivethreeo commented
Um, finch branch is now canary, can you do this against canary?