console log custom razzle config
jaredpalmer/razzle pull request #907
Opened 2019-02-01 11:34 UTC by mschipperheyn

Small change to log the use of a custom `razzle.config.js`. It's always nice to know when things don't work as expected that the custom razzle config was actually loaded.

2019-02-06 08:45 UTC, omdjin approved these changes

2019-02-08 20:46 UTC, jaredpalmer requested changes

2019-02-08 20:46 UTC, jaredpalmer commented on packages/razzle/scripts/build.js
> +    console.log(chalk.yellow('Found custom razzle.config.js'));
Yellow should be reserved for warnings.
```suggestion
    console.log(chalk.dim('Found custom razzle.config.js'));
```

2019-02-08 20:46 UTC, jaredpalmer commented on packages/razzle/scripts/build.js
> +    console.log(`No custom razzle config processed (${errMessage})`);
The problem with this though is that this will _always_ show if there is no `razzle.config.js` (ie. the require() fails).

2020-04-07 22:58 UTC, nimaa77 commented
closed in favor of #1231

2020-04-07 22:58 UTC, closed without merging