Added example with-now-v2
jaredpalmer/razzle pull request #942
Opened 2019-03-02 20:42 UTC by dfreire

Straightforward example to deploy to now v2.

Also see #900

2019-03-12 06:15 UTC, sync commented on examples/with-now-v2/package.json
> +    "start:prod": "NODE_ENV=production node build/server.js"
You could also add a now-build script

2019-04-16 16:45 UTC, jaredpalmer requested changes
Few nits

2019-04-16 16:45 UTC, jaredpalmer commented on examples/with-now-v2/package.json
> +    "razzle": "^2.4.1",
Duplicate deps. Only include devDep

2019-04-16 16:45 UTC, jaredpalmer commented on examples/with-now-v2/package.json
> +    "react-router-dom": "^4.3.1"
Remove react router since it isn’t used

2019-06-27 10:38 UTC, gl0gl0 commented
I've tried this, but I'm getting an error after now deployment that says:
`INTERNAL_MISSING_RESPONSE_FROM_CACHE`
Any ideas? I can't find any documentation about it.

2019-07-17 14:41 UTC, merged